Enhanced delete_security_group function and added list_security_groups
**Added:**

- Introduced a new function `list_security_groups` to list security groups
  based on optional tag-based filters. This function improves the ability
  to dynamically manage security groups by allowing filtering by tags, making
  the management of AWS security groups more flexible and efficient.

**Changed:**

- Updated the `delete_security_group` function to allow deletion by either
  security group ID or name. This update includes the ability to handle multiple
  security group deletions, addressing dependencies by retrying deletion
  up to a maximum number of attempts. This enhancement is crucial for
  managing security groups with dependencies, ensuring a smoother and more
  reliable deletion process.
- Modified `delete_security_group` to utilize `list_security_groups` for
  fetching security group IDs, improving code reusability and efficiency.

**Fixed:**

- Addressed a ShellCheck warning (SC2207) by replacing command substitution
  with a while read loop, enhancing script reliability and compliance with
  best practices.

diff --git a/aws b/aws
--- a/aws
+++ b/aws
@@ -106,38 +106,55 @@ create_ec2_instance() {
 
 # Delete Security Group
 #
-# Deletes a specified security group.
+# Deletes a specified security group by its ID or name.
 #
 # Usage:
+#   delete_security_group "security-group-id"
 #   delete_security_group "security-group-name"
 #
 # Output:
 #   Deletes the specified security group if it exists. If it doesn't exist,
 #   the function outputs a message indicating so.
-#   If the function fails to delete the security group, it retries every
-#   5 seconds until successful.
+#   If the function fails to delete the security group, it retries up to a
+#   maximum number of attempts before giving up.
 #
 # Example(s):
+#   delete_security_group "sg-0123456789abcdef0"
 #   delete_security_group "my-security-group"
-delete_security_group(){
-    SEC_GRP="$1"
-    # Attempt to get the ID of the security group and capture any error message
-    if SEC_GRP_ID=$(aws ec2 describe-security-groups --group-names "$SEC_GRP" --query 'SecurityGroups[0].GroupId' --output text 2> /dev/null); then
-        while true; do
+delete_security_group() {
+    local sec_grp="$1"
+    local sec_grp_ids=()
+    local max_attempts=5
+    local attempt=1
+
+    # Use the list_security_groups function to get the IDs of the matching security groups
+    if [[ "$sec_grp" == sg-* ]]; then
+        sec_grp_ids+=("$sec_grp")
+    else
+        while IFS= read -r line; do
+            sec_grp_ids+=("$line")
+        done < <(list_security_groups "$sec_grp")
+    fi
+
+    for sec_grp_id in "${sec_grp_ids[@]}"; do
+        while (( attempt <= max_attempts )); do
             # Try to delete the security group
-            if aws ec2 delete-security-group --group-id="$SEC_GRP_ID" > /dev/null 2>&1; then
+            if aws ec2 delete-security-group --group-id="$sec_grp_id" > /dev/null 2>&1; then
                 # If successful, exit the loop
-                echo "Successfully deleted security group: $SEC_GRP"
+                echo "Successfully deleted security group with ID: $sec_grp_id"
                 break
             else
-                # If unsuccessful, sleep for 5 seconds and try again
-                echo "Failed to delete security group: $SEC_GRP. Retrying in 5 seconds..."
+                # If unsuccessful, increment the attempt counter and try again
+                echo "Failed to delete security group with ID: $sec_grp_id. Attempt $attempt of $max_attempts. Retrying in 5 seconds..."
+                (( attempt++ ))
                 sleep 5
             fi
         done
-    else
-        echo "Security group $SEC_GRP does not exist, nothing to delete."
-    fi
+
+        if (( attempt > max_attempts )); then
+            echo "Unable to delete security group with ID: $sec_grp_id after $max_attempts attempts."
+        fi
+    done
 }
 
 # Download Bucket
@@ -400,25 +417,6 @@ function get_latest_ami() {
     echo "$AMI_ID"
 }
 
-# List Running Instances
-#
-# Lists all running EC2 instances.
-#
-# Usage:
-#   list_running_instances
-#
-# Output:
-#   Outputs a table of running instances.
-#
-# Example(s):
-#   list_running_instances
-list_running_instances() {
-  aws ec2 describe-instances \
-    --query \
-    "Reservations[*].Instances[*].{InstanceId:InstanceId, VPC:VpcId, Subnet:SubnetId, PublicIP:PublicIpAddress,Name:Tags[?Key=='Name']|[0].Value}" \
-    --filters Name=instance-state-name,Values=running --output json
-}
-
 # List Instance Profiles
 #
 # Lists all instance profiles.
@@ -438,6 +436,56 @@ list_instance_profiles() {
     for INSTANCE_PROFILE_NAME in $INSTANCE_PROFILE_NAMES; do
         echo "$INSTANCE_PROFILE_NAME"
     done
+}
+
+# List Running Instances
+#
+# Lists all running EC2 instances.
+#
+# Usage:
+#   list_running_instances
+#
+# Output:
+#   Outputs a table of running instances.
+#
+# Example(s):
+#   list_running_instances
+list_running_instances() {
+  aws ec2 describe-instances \
+    --query \
+    "Reservations[*].Instances[*].{InstanceId:InstanceId, VPC:VpcId, Subnet:SubnetId, PublicIP:PublicIpAddress,Name:Tags[?Key=='Name']|[0].Value}" \
+    --filters Name=instance-state-name,Values=running --output json
+}
+
+# List Security Groups
+#
+# Lists security groups based on optional filters.
+#
+# Usage:
+#   list_security_groups
+#
+# Output:
+#   Lists the names of the security groups that match the specified filters, if any.
+#   If no filters are specified, all security group names are listed, one per line.
+#
+# Example(s):
+#   list_security_groups
+#   list_security_groups "test-tt-test-*"
+list_security_groups() {
+    local filter="$1"
+    local query_args=()
+
+    # Check if a filter is provided and construct the query argument
+    if [[ -n "$filter" ]]; then
+        query_args=(--filters "Name=group-name,Values=$filter")
+    fi
+
+    # Attempt to list security groups with the given filter
+    local group_names
+    group_names=$(aws ec2 describe-security-groups "${query_args[@]}" --query 'SecurityGroups[*].GroupName' --output text)
+    if [[ $? -eq 0 ]]; then
+        echo "$group_names" | tr '\t' '\n'
+    fi
 }
 
 # Terminate Instance
