Refactored S3 and AWS command handling scripts
**Added:**

- Added `s3.sh` with functions to manage S3 buckets:
  - `clear_and_delete_s3_buckets`: Deletes S3 buckets based on criteria.
  - `download_bucket`: Syncs S3 bucket contents to a local directory.

**Changed:**

- Moved `wait_for_command` function to the bottom of `aws` script for better organization.

**Removed:**

- Removed cloud dotfiles sourcing from `.zshrc` to simplify configuration.

diff --git a/aws b/aws
--- a/aws
+++ b/aws
@@ -1,119 +1,3 @@
-# Download Bucket
-#
-# Syncs the contents of the specified Amazon S3 bucket to the
-# specified local destination directory or to the current directory
-# if no destination is provided.
-#
-# Usage:
-#   download_bucket [bucket-name] [destination-directory]
-#
-# Output:
-#   Syncs the files from the S3 bucket to the local destination.
-#
-# Example(s):
-#   download_bucket "mybucket" "$HOME"
-#   download_bucket "mybucket"
-download_bucket() {
-	bucket="${1}"
-	if [[ -z "${bucket}" ]]; then
-		echo "You need to supply a bucket!"
-		echo "Example: download_bucket mybucket $HOME"
-		return 1
-	fi
-	dest="${2}"
-	if [[ -z "${dest}" ]]; then
-		dest='.'
-	fi
-
-	aws s3 sync "s3://${1}" "${dest}"
-}
-
-# Wait for Command
-#
-# Waits for a previously run command to complete.
-#
-# Usage:
-#   wait_for_command [command_id]
-#
-# Output:
-#   No output, but pauses script execution until the specified command has finished running.
-#
-# Example(s):
-#   wait_for_command "0abcd1234efgh5678"
-wait_for_command() {
-    local command_id=$1
-    local command_status
-
-    while true; do
-        command_status=$(aws ssm list-command-invocations --command-id "$command_id" --details --query 'CommandInvocations[0].Status' --output text)
-
-        if [ -z "$command_status" ]; then
-            echo "Failed to fetch command status."
-            exit 1
-        elif [ "$command_status" = "Success" ]; then
-            break
-        elif [ "$command_status" = "Failed" ]; then
-            echo "Command execution failed."
-            exit 1
-        fi
-
-        echo "Waiting for command to finish..."
-        sleep 5
-    done
-}
-
-# Clean Up and Delete S3 Buckets Based on Criteria
-#
-# This function lists and deletes S3 buckets that match a specified selection criteria.
-# It first deletes all objects (including versions and delete markers) within each bucket,
-# and then deletes the bucket itself. The deletion process is done in parallel for efficiency.
-#
-# Usage:
-#   clear_and_delete_s3_buckets "bucket-selection-criteria"
-#   where "bucket-selection-criteria" is the string used to match bucket names.
-#
-# Output:
-#   Outputs the progress of deleting objects and buckets, including any errors encountered.
-#
-# Example(s):
-#   clear_and_delete_s3_buckets "ttpforge-bucket"
-#   clear_and_delete_s3_buckets "attack-box-bucket"
-#   clear_and_delete_s3_buckets "atomic-red-team-bucket"
-#   clear_and_delete_s3_buckets "my-example-bucket"
-clear_and_delete_s3_buckets() {
-    local bucket_selection_criteria=$1
-
-    if [[ -z "$bucket_selection_criteria" ]]; then
-        echo "No bucket selection criteria provided. Usage: clean_up_s3_buckets <bucket-selection-criteria>"
-        return 1
-    fi
-
-    # List all buckets that match the selection criteria
-    local buckets=()
-    while IFS= read -r line; do
-        buckets+=("$line")
-    done < <(aws s3 ls | grep -i "$bucket_selection_criteria" | awk '{print $3}')
-
-    # Iterate through each bucket and delete its contents and the bucket itself
-    for bucket in "${buckets[@]}"; do
-        (
-            echo "Deleting objects from bucket: ${bucket}"
-
-            # Remove all versions of all objects from the bucket
-            aws s3api list-object-versions --bucket "$bucket" --output json | jq -r '.Versions[] | .Key + " " + .VersionId' | xargs -P 10 -n 2 aws s3api delete-object --bucket "$bucket" --key {} --version-id {}
-
-            # Remove all delete markers (needed for versioned buckets)
-            aws s3api list-object-versions --bucket "$bucket" --output json | jq -r '.DeleteMarkers[] | .Key + " " + .VersionId' | xargs -P 10 -n 2 aws s3api delete-object --bucket "$bucket" --key {} --version-id {}
-
-            echo "Deleting bucket: ${bucket}"
-
-            # Delete the bucket
-            aws s3 rb s3://"$bucket" --force
-        ) &
-    done
-    wait
-}
-
 # Deletes an EKS cluster and its associated node groups
 #
 # This function deletes an Amazon EKS cluster and all of its associated node groups.
@@ -230,3 +114,57 @@ delete_kms_keys_with_string() {
     # Wait for all background processes to complete
     wait
 }
+
+# Wait for Command
+#
+# Waits for a previously run command to complete.
+#
+# Usage:
+#   wait_for_command [command_id]
+#
+# Output:
+#   No output, but pauses script execution until the specified command has finished running.
+#
+# Example(s):
+#   wait_for_command "0abcd1234efgh5678"
+wait_for_command() {
+    local command_id=$1
+    local command_status
+
+    while true; do
+        command_status=$(aws ssm list-command-invocations --command-id "$command_id" --details --query 'CommandInvocations[0].Status' --output text)
+
+        if [ -z "$command_status" ]; then
+            echo "Failed to fetch command status."
+            exit 1
+        elif [ "$command_status" = "Success" ]; then
+            break
+        elif [ "$command_status" = "Failed" ]; then
+            echo "Command execution failed."
+            exit 1
+        fi
+
+        echo "Waiting for command to finish..."
+        sleep 5
+    done
+}
+
+# Source cloud dotfiles
+for provider in "${HOME}/.dotfiles/cloud"/*; do
+  if [[ -d "${provider}" ]]; then
+    for file in "${provider}"/*; do
+      if [[ -f "${file}" && -r "${file}" ]]; then
+        # shellcheck source=/dev/null
+        source "${file}"
+      fi
+      if [[ -d "${file}" ]]; then
+        for script in "${file}"/*; do
+          if [[ -f "${script}" && -r "${script}" ]]; then
+            # shellcheck source=/dev/null
+            source "${script}"
+          fi
+        done
+      fi
+    done
+  fi
+done
