Add several new functions

diff --git a/aws b/aws
--- a/aws
+++ b/aws
@@ -58,6 +58,50 @@ function authorize_security_group_ingress() {
     fi
 }
 
+# Create EC2 Instance
+# Creates an EC2 instance with the specified AMI, instance type, and security group.
+#
+# Usage:
+#   create_ec2_instance
+#
+# Output:
+#   Outputs the ID of the created EC2 instance.
+#
+# Example(s):
+#   create_ec2_instance
+create_ec2_instance() {
+    AMI_ID="$1"
+    INSTANCE_TYPE="${2:-t3.micro}"
+    IAM_INSTANCE_PROFILE="${3:-AmazonSSMInstanceProfileForInstances}"
+    INSTANCE_NAME="${4:-My-EC2-Instance}"
+    SECURITY_GROUP_NAME="${5:-default-sg}"
+    SECURITY_GROUP_DESC="${6:-Default Security Group}"
+    VPC_ID="$7"
+    DEFAULT_SUBNET_ID="$8"
+
+    SECURITY_GROUP_ID=$(authorize_security_group_ingress "$SECURITY_GROUP_NAME" "$SECURITY_GROUP_DESC" "${VPC_ID}" "tcp" 22 "0.0.0.0/0" | tail -n 1)
+
+    INSTANCE_ID=$(aws ec2 run-instances \
+        --image-id "$AMI_ID" \
+        --count 1 \
+        --instance-type "$INSTANCE_TYPE" \
+        --security-group-ids "$SECURITY_GROUP_ID" \
+        --subnet-id "$DEFAULT_SUBNET_ID" \
+        --iam-instance-profile "Name=$IAM_INSTANCE_PROFILE" \
+        --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$INSTANCE_NAME}]" \
+        --query 'Instances[0].InstanceId' \
+        --output text)
+
+    wait_for_initialization
+
+    if [ -z "$INSTANCE_ID" ]; then
+        echo "Failed to create EC2 instance"
+        exit 1
+    fi
+    echo "Created EC2 instance: $INSTANCE_ID" >&2
+    echo "${INSTANCE_ID}"
+}
+
 # Download Bucket
 # Syncs the contents of the specified Amazon S3 bucket to the
 # specified local destination directory or to the current directory
@@ -87,7 +131,57 @@ download_bucket() {
 	aws s3 sync "s3://${1}" "${dest}"
 }
 
+# Find Default Subnet
+# Finds the default subnet ID.
+#
+# Usage:
+#   find_default_subnet
+#
+# Output:
+#   Outputs the default subnet ID.
+#
+# Example(s):
+#   find_default_subnet
+function find_default_subnet() {
+    aws ec2 describe-subnets \
+        --filters "Name=default-for-az,Values=true" \
+        --output text --query 'Subnets[0].SubnetId'
+}
 
+# Find Default VPC
+# Finds the default VPC ID.
+#
+# Usage:
+#   find_default_vpc
+#
+# Output:
+#   Outputs the default VPC ID.
+#
+# Example(s):
+#   find_default_vpc
+function find_default_vpc() {
+    aws ec2 describe-vpcs \
+        --filters "Name=isDefault,Values=true" \
+        --output text --query 'Vpcs[0].VpcId'
+}
+
+# Get Instance Role Credentials
+# Retrieves the IAM role credentials from the specified EC2 instance.
+#
+# Usage:
+#   get_instance_role_credentials
+#
+# Output:
+#   Outputs the IAM role credentials.
+#
+# Example(s):
+#   get_instance_role_credentials
+get_instance_role_credentials() {
+    COMMAND_ID=$(aws ssm send-command --instance-ids "$INSTANCE_ID" --document-name AWS-RunShellScript --parameters 'commands=["curl http://169.254.169.254/latest/meta-data/iam/security-credentials/'"$ROLE_NAME"'"]' --query "Command.CommandId" --output text)
+    wait_for_command "$COMMAND_ID"
+    CREDENTIALS=$(aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query 'StandardOutputContent' --output text)
+    echo "$CREDENTIALS"
+}
 
 # Get Latest AMI
 # Fetches the ID of the latest Amazon Machine Image (AMI) for the
@@ -265,5 +359,60 @@ list_instance_profiles() {
     # For each instance profile, print the name
     for INSTANCE_PROFILE_NAME in $INSTANCE_PROFILE_NAMES; do
         echo "$INSTANCE_PROFILE_NAME"
+    done
+}
+
+# Wait for Command
+# Waits for the previously run command to complete.
+#
+# Usage:
+#   wait_for_command [command_id]
+#
+# Output:
+#   No output, but pauses script execution until the specified command has finished running.
+#
+# Example(s):
+#   wait_for_command "0abcd1234efgh5678"
+wait_for_command() {
+    local command_id=$1
+    local command_status
+
+    while true; do
+        command_status=$(aws ssm list-command-invocations --command-id "$command_id" --details --query 'CommandInvocations[0].Status' --output text)
+
+        if [ -z "$command_status" ]; then
+            echo "Failed to fetch command status."
+            exit 1
+        elif [ "$command_status" == "Success" ]; then
+            break
+        elif [ "$command_status" == "Failed" ]; then
+            echo "Command execution failed."
+            exit 1
+        fi
+
+        echo "Waiting for command to finish..."
+        sleep 5
+    done
+}
+
+# Wait for Initialization
+# Waits until the newly created EC2 instance changes its status
+# from "initializing" to another state, signaling that initialization
+# has completed.
+#
+# Usage:
+#   wait_for_initialization
+#
+# Output:
+#   No output, but pauses script execution until the EC2 instance has finished initializing.
+#
+# Example(s):
+#   wait_for_initialization
+wait_for_initialization() {
+    instance_status="initializing"
+    while [[ "$instance_status" == "initializing" || "$instance_status" == "null" ]]; do
+        instance_status=$(aws ec2 describe-instance-status --instance-id "${INSTANCE_ID}" \
+            | jq -r ".InstanceStatuses[0].InstanceStatus.Status")
+        sleep 10
     done
 }
