Add several new AWS functions

diff --git a/aws b/aws
--- a/aws
+++ b/aws
@@ -102,6 +102,41 @@ create_ec2_instance() {
     echo "${INSTANCE_ID}"
 }
 
+# Delete Security Group
+# Deletes a specified security group.
+#
+# Usage:
+#   delete_security_group "security-group-name"
+#
+# Output:
+#   Deletes the specified security group if it exists. If it doesn't exist,
+#   the function outputs a message indicating so.
+#   If the function fails to delete the security group, it retries every
+#   5 seconds until successful.
+#
+# Example(s):
+#   delete_security_group "my-security-group"
+delete_security_group(){
+    SEC_GRP="$1"
+    # Attempt to get the ID of the security group and capture any error message
+    if SEC_GRP_ID=$(aws ec2 describe-security-groups --group-names "$SEC_GRP" --query 'SecurityGroups[0].GroupId' --output text 2> /dev/null); then
+        while true; do
+            # Try to delete the security group
+            if aws ec2 delete-security-group --group-id="$SEC_GRP_ID" > /dev/null 2>&1; then
+                # If successful, exit the loop
+                echo "Successfully deleted security group: $SEC_GRP"
+                break
+            else
+                # If unsuccessful, sleep for 5 seconds and try again
+                echo "Failed to delete security group: $SEC_GRP. Retrying in 5 seconds..."
+                sleep 5
+            fi
+        done
+    else
+        echo "Security group $SEC_GRP does not exist, nothing to delete."
+    fi
+}
+
 # Download Bucket
 # Syncs the contents of the specified Amazon S3 bucket to the
 # specified local destination directory or to the current directory
@@ -163,6 +198,25 @@ function find_default_vpc() {
     aws ec2 describe-vpcs \
         --filters "Name=isDefault,Values=true" \
         --output text --query 'Vpcs[0].VpcId'
+}
+
+# Get Instances by Tag Name
+# Fetches the ID of the EC2 instances based on a specified tag value.
+#
+# Usage:
+#   find_instance_by_tag "tag-value"
+#
+# Output:
+#   Outputs the ID of the EC2 instances that have the tag "Name" with the specified value.
+#
+# Example(s):
+#   INSTANCES=$(find_instance_by_tag "prod")
+find_instance_by_tag() {
+    INSTANCE_NAME_TAG="$1"
+    # shellcheck disable=SC2016
+    aws ec2 describe-instances \
+        --query 'Reservations[].Instances[?Tags[?Key==`Name` && Value==`'$INSTANCE_NAME_TAG'`]].InstanceId' \
+        --output text
 }
 
 # Get Instance Role Credentials
@@ -362,8 +416,39 @@ list_instance_profiles() {
     done
 }
 
+# Terminate Instance
+# Terminates a specified EC2 instance.
+#
+# Usage:
+#   terminate_instance [instance_id]
+#
+# Output:
+#   Terminates the instance if it's running. If it's already being terminated, the function skips it.
+#   If the instance is in an unexpected state, it throws an error.
+#
+# Example(s):
+#   terminate_instance "i-0abcd1234efgh5678"
+terminate_instance() {
+    local instance_id=$1
+    while true; do
+        instance_status=$(aws ec2 describe-instances --instance-ids "$instance_id" \
+            --query 'Reservations[0].Instances[0].State.Name' --output text --no-cli-pager)
+        if [ "$instance_status" == "terminated" ] || [ "$instance_status" == "shutting-down" ]; then
+            echo "Skipping instance $instance_id which is already $instance_status"
+            break
+        elif [ "$instance_status" == "running" ]; then
+            echo "Terminating instance: $instance_id"
+            aws ec2 terminate-instances --instance-ids "$instance_id" --no-cli-pager
+            break
+        else
+            echo "Unexpected instance status: $instance_status"
+            exit 1
+        fi
+    done
+}
+
 # Wait for Command
-# Waits for the previously run command to complete.
+# Waits for a previously run command to complete.
 #
 # Usage:
 #   wait_for_command [command_id]
