Bug fixes for non-bash shells

diff --git a/bashutils b/bashutils
--- a/bashutils
+++ b/bashutils
@@ -293,35 +293,33 @@ fetchFromGithub() {
     REPO="$AUTHOR/$REPO_NAME"
     assets=$(gh release view $VERSION --repo $REPO --json assets | jq -r '.assets[].name')
 
-    # convert assets to an array
-    # guacinator_1.0.0_checksums.txt guacinator_1.0.0_darwin_amd64v2.tar.gz guacinator_1.0.0_darwin_amd64v3.tar.gz guacinator_1.0.0_darwin_arm64.tar.gz guacinator_1.0.0_linux_amd64v2.tar.gz guacinator_1.0.0_linux_amd64v3.tar.gz guacinator_1.0.0_linux_arm64.tar.gz guacinator_1.0.0_linux_armv6.tar.gz guacinator_1.0.0_linux_armv7.tar.gz 
-    # convert assets to an array
-assets_array=($(echo $assets))
-# Iterate over the array and search for a match
-for asset in "${assets_array[@]}"; do
-    if [[ $asset == *"$os"* && $asset == *"$arch"* ]]; then
-        gh release download $VERSION --repo $REPO --pattern "$asset" -D "/tmp"
-        echo "Download of $REPO_NAME release $VERSION from GitHub is complete."
-        
-        # Extract the tarball
-        pushd "/tmp" || exit
-        extract "/tmp/$asset"
-        
-        for file in *; do
-            if [[ -x "$file" && -f "$file" ]]; then
-                cp "$file" "$HOME/.local/bin/"
-                echo "Copied $file to $HOME/.local/bin/"
-            fi
-        done
-        popd || exit
-        
-        # Cleanup
-        # rm "/tmp/$asset"
-        return 0
-    fi
-done
-    
+    # read assets into an array
+    while IFS= read -r line; do
+        assets_array+=("$line")
+    done < <(echo $assets | tr " " "\n")
+    # Iterate over the array and search for a match
+    for asset in "${assets_array[@]}"; do
+        if [[ $asset == *"$os"* && $asset == *"$arch"* ]]; then
+            gh release download $VERSION --repo $REPO --pattern "$asset" -D "/tmp"
+            echo "Download of $REPO_NAME release $VERSION from GitHub is complete."
 
+            # Extract the tarball
+            pushd "/tmp" || exit
+            extract "/tmp/$asset"
+
+            for file in *; do
+                if [[ -x "$file" && -f "$file" ]]; then
+                    cp "$file" "$HOME/.local/bin/"
+                    echo "Copied $file to $HOME/.local/bin/"
+                fi
+            done
+            popd || exit
+
+            # Cleanup
+            rm "/tmp/$asset"
+            return 0
+        fi
+    done
 
     echo "No relevant release found for OS: $os, architecture: $arch"
     return 1
