Created new `common` function and updated `terraform` script.
**Added:**

- Common Functions File - Introduced `common` file containing reusable shell
  functions, including `ru_sure` for user confirmation prompts.
- `ru_sure` Function - Added a new function `ru_sure` to handle user
  confirmation with custom messages in shell scripts.

**Changed:**

- `terraform` Script - Updated the `terraform` script to source the `common`
  functions file and use the `ru_sure` function for confirmation in the
  `nuke_terragrunt_state` function.
- `install_dot_files.sh` Script - Added `common` to the list of files to be
  installed, ensuring the new common functions are available.

**Removed:**

- Inline Confirmation Prompt - Removed the inline confirmation prompt from the
  `nuke_terragrunt_state` function in the `terraform` script, replacing it with
  the `ru_sure` function from the `common` file.

diff --git a/terraform b/terraform
--- a/terraform
+++ b/terraform
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 # Taints all Terraform-managed resources in the current state
 #
 # This function taints all Terraform-managed resources in the current state,
@@ -29,5 +31,39 @@ taint_terraform_resources() {
                 echo "Tainted resource $resource"
             fi
         fi
+    done
+}
+
+# Removes all resources from Terragrunt state after confirmation
+#
+# This function prompts the user for confirmation before removing all resources
+# from the Terragrunt state. It lists all resources in the state and removes
+# them one by one, displaying the progress.
+#
+# Usage:
+#   nuke_terragrunt_state
+#
+# Output:
+#   Displays the progress of removing each resource, including any errors
+#   encountered during the process.
+#
+# Example(s):
+#   nuke_terragrunt_state
+nuke_terragrunt_state() {
+    if [[ ! -f $HOME/.dotfiles/common ]]; then
+        echo "Error: Unable to find common functions file"
+        return 1
+    fi
+
+    # shellcheck disable=SC1091
+    source "$HOME/.dotfiles/common"
+    if ! ru_sure "Are you sure you want to remove all resources from Terragrunt state?"; then
+        return
+    fi
+
+    # List all Terragrunt state resources and remove them
+    terragrunt state list | while read -r resource; do
+        echo "Removing $resource..."
+        terragrunt state rm "$resource"
     done
 }
