Fixed test action and other bugs

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -17,8 +17,92 @@ on:
         default: jayson.e.grace@gmail.com
 
 jobs:
-  setup:
-    name: Install and test my personal dotfiles
+  # setup:
+  #   name: Install and test my personal dotfiles
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     matrix:
+  #       os: [ubuntu-latest, macos-latest]
+  # steps:
+  #   - name: Set up git repository
+  #     uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+  #     with:
+  #       submodules: recursive
+
+  # - name: Install asdf cli
+  #   uses: asdf-vm/actions/setup@6a442392015fbbdd8b48696d41e0051b2698b2e4 # v2
+
+  # - name: Set up Python
+  #   uses: actions/setup-python@v4
+
+  # - name: Install dependencies
+  #   run: |
+  #     if [[ "${RUNNER_OS}" == "Linux" ]]; then
+  #         sudo apt-get update
+  #         sudo apt-get install -y curl git zsh
+  #     fi
+  #     python3 -m pip install ansible
+  #     ansible-galaxy collection install git+https://github.com/cowdogmoo/workstation.git,main
+
+  # - name: Install the dotfiles
+  #   run: |
+  #     chmod +x install_dot_files.sh
+  #     if ./install_dot_files.sh; then
+  #       echo "Dotfiles installed successfully"
+  #     else
+  #       echo "Dotfiles installation failed"
+  #       exit 1
+  #     fi
+
+  bats_tests:
+    # needs: setup
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest, macos-latest]
+    steps:
+      - name: Set up git repository
+        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+        with:
+          submodules: recursive
+
+      - name: Install dependencies
+        run: |
+          if [[ "${RUNNER_OS}" == "Linux" ]]; then
+              sudo apt-get update
+              sudo apt-get install -y curl git zsh
+          fi
+          python3 -m pip install ansible
+          ansible-galaxy collection install git+https://github.com/cowdogmoo/workstation.git,main
+
+      - name: Install the dotfiles
+        run: |
+          set -x # Enable verbose output
+          chmod +x install_dot_files.sh
+          if ./install_dot_files.sh; then
+            echo "Dotfiles installed successfully"
+          else
+            echo "Dotfiles installation failed"
+            exit 1
+          fi
+
+      - name: Setup BATS
+        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1
+        with:
+          bats-version: 1.2.1
+
+      - name: Set up temporary git config to satisfy tests
+        run: |
+          git config --global user.email "you@example.com"
+          git config --global user.name "Your Name"
+
+      - name: Run Bats tests
+        run: |
+          bats tests/test-go.bats
+          # bats tests/{test-go,test-bashutils}.bats # for when I have time to make things work in github actions
+
+  dotfile_test:
+    # needs: setup
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
@@ -38,101 +122,11 @@ jobs:
               sudo apt-get update
               sudo apt-get install -y curl git zsh
           fi
-
-          # Get ohmyzsh
-          wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
-          sh install.sh --unattended
-
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.13.0"
-
-      - name: Install dependencies
-        run: |
           python3 -m pip install ansible
           ansible-galaxy collection install git+https://github.com/cowdogmoo/workstation.git,main
 
-      - name: Run dotfiles installation script
-        run: bash install_dot_files.sh
-
-  bats_tests:
-    needs: setup
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ubuntu-latest, macos-latest]
-    steps:
-      - name: Set up git repository
-        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-        with:
-          submodules: recursive
-
-      - name: Setup BATS
-        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1
-        with:
-          bats-version: 1.2.1
-
-      - name: Install dependencies
-        run: |
-          if [[ "${RUNNER_OS}" == "Linux" ]]; then
-              sudo apt-get update
-              sudo apt-get install -y curl git zsh
-              # Fix permissions to avoid annoying message
-              sudo chmod -R 755 /usr/share/zsh
-              sudo chmod -R 755 /usr/share/zsh/vendor-completions
-              # Resource: https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os
-          fi
-
-          # Get ohmyzsh
-          bash -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
-
-      - name: Set up additional files for testing
-        run: |
-          mkdir -p $HOME/.dotfiles
-          cp -r files $HOME/.dotfiles
-          # Required for asdf
-          cp -r .tool-versions $HOME/.tool-versions
-
-      - name: Set up temporary git config to satisfy tests
-        run: |
-          git config --global user.email "you@example.com"
-          git config --global user.name "Your Name"
-
-      # - name: Install asdf cli
-      #   uses: asdf-vm/actions/install@v2
-
-      - name: Run Bats tests
-        run: |
-          bats tests/test-go.bats
-          # bats tests/{test-go,test-bashutils}.bats # for when I have time to make things work in github actions
-
-  dotfile_test:
-    needs: setup
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ubuntu-latest, macos-latest]
-    steps:
-      - name: Set up git repository
-        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-        with:
-          submodules: recursive
-
-      - name: Install dependencies
-        run: |
-          if [[ "${RUNNER_OS}" == "Linux" ]]; then
-              sudo apt-get update
-              sudo apt-get install -y curl git zsh
-              # Fix permissions to avoid annoying message
-              sudo chmod -R 755 /usr/share/zsh
-              sudo chmod -R 755 /usr/share/zsh/vendor-completions
-              # Resource: https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os
-          fi
-
       - name: Install the dotfiles
         run: |
-          set -x # Enable verbose output
           chmod +x install_dot_files.sh
           if ./install_dot_files.sh; then
             echo "Dotfiles installed successfully"
@@ -143,11 +137,13 @@ jobs:
 
       - name: Confirm dotfiles are installed and working
         run: |
+          source ~/.zshrc
+          cat ~/.zshrc
+          source ~/.dotfiles/python
           ls -lart ~/.dotfiles
-          source ~/.zshrc # Required for run_playbook
-          ipaddr
-          go version
-          cat ~/.cobra.yaml
+          which ipaddr
+          which go
+          which run_playbook
         shell: zsh {0}
 
         # # For debugging:
